export { Button } from './Button';
export { Title } from './Title';
export { Link } from './Link'
export { Main } from './Main'
export { Medium } from './Medium'
export { Small } from './Small'
export { RublesLarge } from "./RublesLarge"
export { RublesSmall } from "./RublesSmall"
export { Error } from './Error'
export { Tertiary } from './Tertiary'
